### ISSUE TITLE
Add OpenWrt package

### ISSUE THREAD

**Issue by roger-** [teffalump/adblock#1]
Would be nice if this were an OpenWrt package. Wouldn't be hard to do if the author is interested.

**Comment by teffalump** [comment]
Yeah, that was suggested on the gist thread. I'm interested, but I'm not too familiar how to do the packaging, etc. Hehe.

**Comment by teffalump** [comment]
If you are on Gargoyle, @lantis1008 has a plugin. =-) I'm working on doing a general OpenWRT package, so we'll see how quickly I can convert his work. =-)

https://github.com/lantis1008/gargoyle-plugin-adblock

**Comment by roger-** [comment]
FYI there's now another OpenWrt ad blocker [here](https://github.com/openwrt/packages/tree/master/net/adblock/files/etc/adblock).

**Comment by lantis1008** [comment]
Looks comprehensive.

**Comment by teffalump** [comment]
Yeah, looks interesting. Maybe I can push people over to that, instead of doing a rival package. ;-)

**Comment by dvdsmpsn** [comment]
The other OpenWrt ad blocker is here: https://github.com/openwrt/packages/tree/master/net/adblock/files

@roger-'s link seems to be broken now :(

**Comment by roger-** [comment]
@dvdsmpsn: Thanks, looks like the file was moved.

@teffalump: Turns out @dibdot's adblock has somewhat steep memory/storage requirements and may not be adequate for many low-power devices (e.g. with 100's KB storage and <= 64 MB RAM). Maybe there's room for a more minimal/efficient alternative?

**Comment by dibdot** [comment]
Sorry, won't hijack this thread, but I've got a notification from github...;-)
@roger-: There is a close connection between number of activated adblock sites/lists and space requirements ... the default configuration should run just fine, even on low power devices. The adblock package itself has nearly "no" space requirements.

**Comment by roger-** [comment]
@dibdot: I was going by the discussion [here](https://forum.openwrt.org/viewtopic.php?id=59803&p=2) that indicated issues with <= 64 MB RAM and no external swap. If this is incorrect or no longer the case then great!

(Sorry for sidetracking the discussion.)

**Comment by lantis1008** [comment]
What he's saying is that if someone activated every ad source included in the package then you run into space requirements. These files get loaded into RAM for the sort procedure I believe which is what causes the crash. 

In my personal opinion, 2-3 is all that is required. There's a large amount of overlap.

**Comment by teffalump** [comment]
I agree with @lantis1008 about the lists, only 2 really required. I have a hunch that 1-5% of the domains account for 95+% of the ads, or something very skewed. Hehe. I should add a pull request to @dibdot to add adaway (good mobile list).

**Comment by dibdot** [comment]
@teffalump: goog idea - added in 0.22.3 (not released yet) ...;-)

**Comment by teffalump** [comment]
@dibdot: Sorry I didn't respond to this, thought I did. Thanks for adding it! On a similar note, I need to start pushing people to your work, and move away from the hack-y script. =-)
