### ISSUE TITLE
 iptables-mod-nat-extra 15.05 rc3

### ISSUE THREAD

**Issue by shaboyi999** [teffalump/adblock#2]
Installing iptables-mod-nat-extra...
Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for iptables-mod-nat-extra:
-      kernel (= 3.18.17-1-5dcb66d04a38219f7fd91c748f0e9a32) *
- opkg_install_cmd: Cannot install package iptables-mod-nat-extra.

---

15.05 rc3 is 3.18.20

Does this mean I need wait for a updated iptables-mod-nat-extra to get it work?

**Comment by teffalump** [comment]
Someone else had a similar issue, and I don't exactly know how they worked it (if they did). For them, they noticed that it was still working, even without installing the package... that is, it was already installed somehow. Also, you can look at the [development package snapshots](https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/base/) for the newest one (I think I gave you the correct link). /etc/opkg.conf should show you where your packages are coming from. Check to see if ads are being blocked. We can go from there, I suppose. Luck! =-)
