### ISSUE TITLE
IP exemptions do not work

### ISSUE THREAD

**Issue by teffalump** [teffalump/adblock#3]
It seems that the iprange exemptions do not work. At all. I need to look into it.

**Comment by lantis1008** [comment]
They actually do work. The thing is the client needs to then use a different address for their DNS requests, not just the router, otherwise they'll continue to have their ads blocked.
I don't know of a way of forcing this.

**Comment by teffalump** [comment]
The rule works, but the client has the router IP as its DNS server, consequently the router still blocks the ad. Is that right? Only way, from what I understand you are saying, is to force the client to use a non-router DNS server (e.g., 8.8.8.8). Or?

If that is the case, I wonder if we can use conditional DNS forwarding?

**Comment by lantis1008** [comment]
That is correct. Conditional forwarding might be the go. 
Can you match multiple ipranges in the one rule?
-m ! ipranges range-one -m ! ipranges range-two etc.?

**Comment by teffalump** [comment]
Yes, I believe so - from the man page: "You can specify multiple extended match modules in one line." I assume that applies to multiple entries of the same match module. I hope. =-)
