### ISSUE TITLE
Adblock over VPN without DNS leaks

### ISSUE THREAD

**Issue by dvdsmpsn** [teffalump/adblock#6]
I have my router connected to a [VPN provider](https://github.com/dvdsmpsn/privateinternetaccess-on-openwrt). 

Running adblock for the first time:

```
root@OpenWrt:~# sh /etc/adblock.sh -f
iptables-mod-nat-extra is installed!
Updating config...
HINT: localservice is set to 1
    Adblocking (and router DNS) over a VPN may not work
    To allow VPN router DNS, manually set localservice to 0
Downloading hosts lists...
```

As suggested, I then changed

```
     option localservice '1'
```

to 

```
      option localservice '0'
```

in `/etc/config/dhcp` 

This results in a DNS leak. Can you think of a way around this? What would you recommend?

**Comment by teffalump** [comment]
@dvdsmpsn: If I understand you, the DNS requests (from the router) are not going over the VPN? That is, you ask the router for domain X, it doesn't have it cached/null-routed, so it makes a normal DNS query to, say, google dns, but it is not over the VPN?

Look [here](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) at the section on **--server**. From the page:

> If an interface name is given, then queries to the server will be forced via that interface

I would suggest that you try specifying the interface for the outbound DNS request -- in this case, **tun0** -- in the server section of the dhcp config. The DNS request should, then, be routed through the VPN (we hope). The syntax is somewhat arcane, so keep trying (I've never done this exactly). If that works, get back to me so I can add it to the script. If not, we'll think this over some more. =-)

**Comment by dvdsmpsn** [comment]
@teffalump Thanks for the response. I'm still trying to figure this out. Here's what I've done so far:

In `/etc/config/dhcp` I changed this line:

```
        option localservice '1'
```

to

```
        option localservice '0'
```

and added this line directly below it:

```
        option server '@tun0'
```

Toggling adblock: 

```
sh /etc/adblock.sh -t
```

...results from [DNS Leak Test](https://www.dnsleaktest.com) suggests that the DNS requests going via are not going over the VPN, so show details of my ISP :(

I'll keep trying to figure this out.

**Comment by teffalump** [comment]
@dvdsmpsn: Hmm.... I'm wondering if it is defaulting to the ISP DNS servers. The traffic could be going over the VPN,  but still using the ISP DNS servers. On the server line, add opendns or Google DNS servers in addition to the interface. Also, you can use tcpdump on the router to see if there are unencrypted DNS requests. Something like:

```
tcpdump -i <interface> udp port 53
```

To check for unencrypted DNS requests leaving on the non-vpn interface. ;-)
