### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by RonnieTiger** [teffalump/adblock#8]
I get the following output when toggling the script (in either direction)

root@OpenWrt:/etc# ./adblock.sh -t
Turning on!
Updating config...
**uci: Parse error (unterminated ') at line 4, byte 20**
Restarting firewall...
Restarting dnsmasq...
Restarting uhttpd...
Restarting cron...
root@OpenWrt:/etc# nano adblock.sh

**Comment by teffalump** [comment]
Hey, sorry about delay. Hmm... could do

```
$ uci show
```

...to see if there are problems with the config file. Looks like your config got messed up? Maybe script did it?

**Comment by RonnieTiger** [comment]
Same error appears right at the bottom, so it looks like a uci error. last block it spits out are the wireless settings, but i checked /etc/config/wireless and i can't see any unclosed blocks.. curious.

**Comment by teffalump** [comment]
Curious, curious... Are there _any_ single quotes in the config? Like, the wireless SSID? E.g., "Ron's WIFI"?
