### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by jackivanov** [teffalump/adblock#9]
Hello!

I faced an issue while surfing in Safari with adblock enabled.
Some of sites are not loading, because Safari tries to load 0.0.0.0 or 127.0.0.1 (the endpoint does not matter for Safari actually) and stops load the page because can't load the elements with ads.
A solution is to modify the endpoint IP to the local IP of your router or run a simple web server locally on your mac. But it's not a good solution, because if the ads are placed on https Safari will notify you about the certificate each time and that's annoying.

Firewall on mac is enabled and I was trying to create a rules to reject the connections, but doesn't seem to help.
`block return in quick on lo0 proto tcp from 127.0.0.1 to 127.0.0.1 port { http https }`

Does anyone know more proper solution?

Thanks

Here is a screenshot from the web inspector http://i.imgur.com/8sXBN1N.png

**Comment by teffalump** [comment]
Hiya!

Thanks for the interest. To be honest, this script is unmaintained. There are much better projects out there, two of which I mention in the README. I'm going to close this. 

All the best.
